#!/bin/bash

DC=$(slapcat | cut -d" " -f2 | grep ^dc -m1)
DOMAIN=$(hostname -d)

HOSTNAME=$(hostname -f)

function randpass() {
  [ "$2" == "0" ] && CHAR="[:alnum:]" || CHAR="[:graph:]"
    cat /dev/urandom | tr -cd "$CHAR" | head -c ${1:-32}
    echo
}

cd /root/

#Jappix
mkdir -p /var/www/yunohost/chat
cp config/apache2/chat /etc/apache2/sites-available/
cp config/apache2/bind /etc/apache2/sites-available/
wget http://chili.kload.fr/attachments/download/23/jappix-spaco-0.9.zip
unzip jappix-spaco-0.9.zip
mv jappix/* /var/www/yunohost/chat/
cp -r config/jappix/* /var/www/yunohost/chat/store/
chmod 777 /var/www/yunohost/chat/store/*
chown -R www-data:www-data /var/www/yunohost/chat/
a2ensite chat bind
