#!/bin/bash

DC=$(slapcat | cut -d" " -f2 | grep ^dc -m1)
DOMAIN=$(hostname -d)

HOSTNAME=$(hostname -f)

function randpass() {
  [ "$2" == "0" ] && CHAR="[:alnum:]" || CHAR="[:graph:]"
    cat /dev/urandom | tr -cd "$CHAR" | head -c ${1:-32}
    echo
}

cd /root/

#Tiny Tiny RSS
wget http://chili.kload.fr/attachments/download/24/tt-rss-1.5.10.tar.gz
tar -xvzf tt-rss-1.5.10.tar.gz
mv tt-rss-1.5.10/* /var/www/yunohost/rss/
TTRSS=$(randpass 10 0)
mysql -e "create database ttrss;"
mysql -e "GRANT ALL PRIVILEGES ON ttrss.* to 'ttrss'@'localhost' IDENTIFIED BY '$TTRSS';"
mysql ttrss < /var/www/yunohost/rss/schema/ttrss_schema_mysql.sql
sed -i "s/passmysql/$TTRSS/g" config/ttrss/config.php
cp config/ttrss/config.php /var/www/yunohost/rss/
chown -R www-data:www-data /var/www/yunohost/rss/
