#!/bin/bash

DC=$(slapcat | cut -d" " -f2 | grep ^dc -m1)
DOMAIN=$(hostname -d)

HOSTNAME=$(hostname -f)

function randpass() {
  [ "$2" == "0" ] && CHAR="[:alnum:]" || CHAR="[:graph:]"
    cat /dev/urandom | tr -cd "$CHAR" | head -c ${1:-32}
    echo
}

cd /root/

#Radicale
pip install radicale
mkdir /var/www/.config/
chown www-data:www-data /var/www/.config/
cp config/radicale/radicale.wsgi /var/www/yunohost/sync/
chown -R www-data:www-data /var/www/yunohost/sync/
