#!/bin/bash

CONF="/etc/yunohost/"
TMP="/tmp/"
DEST="/var/www/yunohost/"

for app in jappix roundcube roundcube_plugins ttrss
do
        VERSION=$(grep version $CONF$app | cut -d"=" -f2)
        UPDATE=$(grep update $CONF$app | cut -d"=" -f2)
        URL=$(grep url $CONF$app | cut -d"=" -f2)
        CONFIG=$(grep config $CONF$app | cut -d"=" -f2)

        wget -q $UPDATE -P $TMP

        NEWVERSION=$(grep version $TMP$app | cut -d"=" -f2)
        NEWUPDATE=$(grep update $TMP$app | cut -d"=" -f2)
        NEWURL=$(grep url $TMP$app | cut -d"=" -f2)
        NEWCONFIG=$(grep config $TMP$app | cut -d"=" -f2)
        NEWFILE=$(echo $NEWURL | awk -F"/" '{print $NF}')
	MD5=$(grep md5 $TMP$app | cut -d"=" -f2)

        rm -Rf $TMP$app

        if [ "$NEWVERSION" != "$VERSION" ]
        then
                echo "$app is updated"
                if [ "$1" = "update" ]
                then
                        wget -q $NEWURL -P $TMP
			echo "$MD5  $TMP$NEWFILE" | md5sum -c -
                        TYPE=$(echo ${NEWFILE##*.})
                        if [ "$TYPE" = "zip" ]
                        then
                                unzip $TMP$NEWFILE -d $TMP"update/"
                        else
                                tar -xvzf $TMP$NEWFILE $TMP"update/"
                        fi

			case $app in
			jappix)
				echo "update jappix"
				rm $TMP$NEWFILE
				rm -Rf $TMP"update/"
			;;
			roundcube)
				echo "update roundcube"
			;;
			roundcube_plugins)
                                echo "update roundcube plugins"
                        ;;
			ttrss)
                                echo "update tiny tiny rss"
                        ;;

			esac
                fi
        else
                        echo "$app is up to date"
        fi
done
